# Generated by Django 2.2.4 on 2019-10-06 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('assignee', models.IntegerField(choices=[(0, 'Alex'), (1, 'Marissa')])),
                ('cadence', models.PositiveSmallIntegerField(choices=[(0, 'Weekly'), (1, 'Monthly')])),
                ('next_due_date', models.DateField()),
            ],
        ),
    ]
