version: '3'

services:

  db:
    image: postgres

  web:
    image: arecker/portal:latest
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: portal.settings.prod
    ports: ["8000:8000"]
    depends_on: ["db"]
    command: |
      python manage.py migrate
