version: '3'

services:
  proxy:
    image: arecker/hub-proxy:latest
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.proxy

  web:
    image: arecker/hub:latest
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.web
