version: '3'

services:
  web:
    image: arecker/hub-web:latest
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.web

  proxy:
    image: arecker/hub-proxy:latest
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.proxy
