
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: hub-db-pv-volume
  labels:
    app: hub
spec:
  storageClassName: generic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: archive.local
    path: /mnt/scratch/hub
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hub-db-pv-claim
  labels:
    app: hub
spec:
  storageClassName: generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hub-db
  labels:
    app: hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hub
        service: hub-db
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: secretboi
          image: arecker/secretboi:latest
          imagePullPolicy: Always
          env:
            - name: ONLY_RUN_ONCE
              value: 'true'
            - name: RECURSE_SECRETS
              value: 'true'
            - name: SECRET_HUB
              value: /hub
            - name: VAULT_ADDR
              value: http://vault.local
            - name: VAULT_ROLE
              value: hub
          volumeMounts:
            - name: secrets
              mountPath: /secrets
        - name: postgres-data-permissions
          image: busybox
          imagePullPolicy: Always
          command: ["/bin/chmod", "-R", "777", "/data"]
          volumeMounts:
            - name: hub-db-data
              mountPath: /data
      containers:
        - name: postgres
          image: postgres:11.5
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: hub
            - name: POSTGRES_USER_FILE
              value: /secrets/HUB/db_username
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/HUB/db_password
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: hub-db-data
      volumes:
        - name: secrets
          emptyDir:
            medium: Memory
        - name: hub-db-data
          persistentVolumeClaim:
            claimName: hub-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: hub-db
  labels:
    app: hub
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    service: hub-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hub-web
  labels:
    app: hub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hub
        service: hub-web
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
        - name: secrets
          image: arecker/secretboi:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: ONLY_RUN_ONCE
              value: 'true'
            - name: VAULT_ADDR
              value: 'http://vault.local'
            - name: VAULT_ROLE
              value: 'hub'
            - name: SECRET_HUB
              value: /hub
            - name: RECURSE_SECRETS
              value: 'true'
      containers:
        - name: web
          image: arecker/hub-web:latest
          command: ["./entry.sh"]
          args: ["web"]
          imagePullPolicy: Always
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: hub.settings.prod
            - name: DEBUG
              value: 'False'
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - mountPath: /media/
              name: media
      volumes:
        - name: secrets
          emptyDir:
            medium: Memory
        - name: media
          nfs:
            server: archive.local
            path: /mnt/scratch/farm/hub/media
---
apiVersion: v1
kind: Service
metadata:
  name: hub-web
  labels:
    app: hub
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    service: hub-web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hub-proxy
  labels:
    app: hub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hub
        service: hub-proxy
    spec:
      volumes:
        - name: media
          nfs:
            server: archive.local
            path: /mnt/scratch/farm/hub/media      
      containers:
        - name: proxy
          image: arecker/hub-proxy:latest
          imagePullPolicy: Always
          env:
            - name: UPSTREAM_DNS
              value: hub-web.default.svc.cluster.local
            - name: UPSTREAM_HOSTNAME
              value: hub.local
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /usr/share/nginx/html/media/
              name: media
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: hub
  labels:
    app: hub
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    service: hub-proxy
