# Generated by Django 2.2.4 on 2019-09-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlychore',
            name='next_due',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='weeklychore',
            name='next_due',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
