# Generated by Django 2.2.4 on 2019-09-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_auto_20190904_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlychore',
            name='last_completed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monthlychore',
            name='next_due',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='weeklychore',
            name='last_completed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weeklychore',
            name='next_due',
            field=models.DateField(editable=False, null=True),
        ),
    ]
