FROM python:3
MAINTAINER Alex Recker <alex@reckerfamily.com>

ARG UID=1001
ARG GID=1001

# Create an app user
RUN groupadd -g $GID -o app
RUN useradd -u $UID -g $GID -ms /bin/bash app
WORKDIR /home/app

# Install requirements
ADD requirements/*.txt requirements/
RUN pip install -r requirements/prod.txt

# Set up environment
USER app
ENV PS1 "\u@\h:\w\$ "
RUN rm -rf .bashrc .profile .bash_logout

# Move code over
ADD . .

# Default
CMD ["bash"]
