FROM nginx:stable
MAINTAINER Alex Recker <alex@reckerfamily.com>
COPY configs/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
ADD static /usr/share/nginx/html/static
COPY entry.sh /root/entry.sh
CMD ["/root/entry.sh", "proxy"]
