FROM nginx:stable
MAINTAINER Alex Recker <alex@reckerfamily.com>
COPY configs/nginx.conf /etc/nginx/nginx.conf
COPY static /usr/share/nginx/html
ADD entry.sh /home/root/entry.sh
CMD ["/home/root/entry.sh"]
